export const FETCH_FEEDS = "FETCH_FEEDS";
export const CURRENT_PAGE_NUMBER = "CURRENT_PAGE_NUMBER";
export const CHART_DATA = "CHART_DATA";
export const INCREASE_UP_VOTE = "INCREASE_UP_VOTE";
export const REMOVE_SELECTED_HIT = "REMOVE_SELECTED_HIT";